### ISSUE TITLE
Cisco Switch - Error(Connected: But no metrics were returned when polling)

### ISSUE THREAD

**Issue by fenghaimeng** [BraydenNeale/Dynatrace-SNMP#3] opened 2019-03-18 02:22 UTC
What is the problem? Snmp is already connected.

**Comment by BraydenNeale** [comment] 2019-03-18 02:57
You are right, SNMP connected to the device fine, which means that IP, credentials and access control is valid. However polling for the specific MIBs did not return any metrics to be able to send back to the Dynatrace Server.

Usually this error occurs because:
The extension makes a single UDP connection polling attempt on each MIB. If the device doesn't respond to this then no metrics are returned until the next attempt 1 minute later. The Dynatrace UI won't let you add a device in when an error was returned, but will keep monitoring once the first connection is established. So you could try to connect a few times until you get that green tick. Any missed polling in future would just be a blip in the charts. 

This is to ensure minimal overhead. You could be more aggressive in your polling by increasing the values for timeout and retries in:
`def snmp_connect_bulk(self, oids, timeout=2, retries=0):`

It could also be the case that:
- The device doesn't support either MIB that is polled (Host-Resource-MIB or  IF-MIB)
Although I haven't encountered that on anything yet, Generally at least one of these will return metrics. e.g. Cisco won't respond to Host-Resource.

What device type are you polling?

**Comment by fenghaimeng** [comment] 2019-03-18 03:07
> 因

The Cisco switch model is Cisco WS-C2950-24

**Comment by fenghaimeng** [comment] 2019-03-18 03:54
> You are right, SNMP connected to the device fine, which means that IP, credentials and access control is valid. However polling for the specific MIBs did not return any metrics to be able to send back to the Dynatrace Server.
> 
> Usually this error occurs because:
> The extension makes a single UDP connection polling attempt on each MIB. If the device doesn't respond to this then no metrics are returned until the next attempt 1 minute later. The Dynatrace UI won't let you add a device in when an error was returned, but will keep monitoring once the first connection is established. So you could try to connect a few times until you get that green tick. Any missed polling in future would just be a blip in the charts.
> 
> This is to ensure minimal overhead. You could be more aggressive in your polling by increasing the values for timeout and retries in:
> `def snmp_connect_bulk(self, oids, timeout=2, retries=0):`
> 
> It could also be the case that:
> 
> * The device doesn't support either MIB that is polled (Host-Resource-MIB or  IF-MIB)
>   Although I haven't encountered that on anything yet, Generally at least one of these will return metrics. e.g. Cisco won't respond to Host-Resource.
> 
> What device type are you polling?



> You are right, SNMP connected to the device fine, which means that IP, credentials and access control is valid. However polling for the specific MIBs did not return any metrics to be able to send back to the Dynatrace Server.
> 
> Usually this error occurs because:
> The extension makes a single UDP connection polling attempt on each MIB. If the device doesn't respond to this then no metrics are returned until the next attempt 1 minute later. The Dynatrace UI won't let you add a device in when an error was returned, but will keep monitoring once the first connection is established. So you could try to connect a few times until you get that green tick. Any missed polling in future would just be a blip in the charts.
> 
> This is to ensure minimal overhead. You could be more aggressive in your polling by increasing the values for timeout and retries in:
> `def snmp_connect_bulk(self, oids, timeout=2, retries=0):`
> 
> It could also be the case that:
> 
> * The device doesn't support either MIB that is polled (Host-Resource-MIB or  IF-MIB)
>   Although I haven't encountered that on anything yet, Generally at least one of these will return metrics. e.g. Cisco won't respond to Host-Resource.
> 
> What device type are you polling?

@BraydenNeale 
What device type are you polling?

**Comment by fenghaimeng** [comment] 2019-03-18 04:32
> 你说得对，SNMP连接到设备很好，这意味着IP，凭证和访问控制是有效的。但是，对特定MIB的轮询未返回任何指标，无法发送回Dynatrace服务器。
> 
> 通常会发生此错误的原因是：
> 扩展在每个MIB上进行单个UDP连接轮询尝试。如果设备没有响应，则在1分钟后的下一次尝试之前不会返回任何指标。Dynatrace UI不允许您在返回错误时添加设备，但会在建立第一个连接后继续监视。因此，您可以尝试连接几次，直到您获得绿色勾选。未来任何错过的民意调查都只是图表中的一个小点。
> 
> 这是为了确保最小的开销。通过增加超时和重试的值，您可以更加积极地进行轮询：
> `def snmp_connect_bulk(self, oids, timeout=2, retries=0):`
> 
> 也可能是这样的情况：
> 
> * 设备不支持轮询的MIB（Host-Resource-MIB或IF-MIB）
>   虽然我还没有遇到任何问题，但通常至少有一个会返回指标。例如思科不会响应主机资源。
> 
> 您轮询的设备类型是什么？

@BraydenNeale 
The device is a cisco switch model is Cisco WS-C2950-24.
what should I do?

**Comment by fenghaimeng** [comment] 2019-03-18 04:33
> You are right, SNMP connected to the device fine, which means that IP, credentials and access control is valid. However polling for the specific MIBs did not return any metrics to be able to send back to the Dynatrace Server.
> 
> Usually this error occurs because:
> The extension makes a single UDP connection polling attempt on each MIB. If the device doesn't respond to this then no metrics are returned until the next attempt 1 minute later. The Dynatrace UI won't let you add a device in when an error was returned, but will keep monitoring once the first connection is established. So you could try to connect a few times until you get that green tick. Any missed polling in future would just be a blip in the charts.
> 
> This is to ensure minimal overhead. You could be more aggressive in your polling by increasing the values for timeout and retries in:
> `def snmp_connect_bulk(self, oids, timeout=2, retries=0):`
> 
> It could also be the case that:
> 
> * The device doesn't support either MIB that is polled (Host-Resource-MIB or  IF-MIB)
>   Although I haven't encountered that on anything yet, Generally at least one of these will return metrics. e.g. Cisco won't respond to Host-Resource.
> 
> What device type are you polling?

@BraydenNeale 
The device is a cisco switch model is Cisco WS-C2950-24.
what should I do?

**Comment by fenghaimeng** [comment] 2019-03-18 06:45
@BraydenNeale 
I am very anxious now, I hope to get your help.

**Comment by BraydenNeale** [comment] 2019-03-18 08:40
I'll have to validate against a switch when I'm onsite again.
There could be an issue with trying to pull back metrics from so many interfaces, I've polled Cisco routers successfully before, haven't confirmed against a switch.

One thing I'm working on is forks to better suit vendor appliances.
e.g. Cisco specific - using Cisco-Process-MIB to return additional more meaningful metrics.

I'll keep you updated

**Comment by fenghaimeng** [comment] 2019-03-18 10:42
> I'll have to validate against a switch when I'm onsite again.
> There could be an issue with trying to pull back metrics from so many interfaces, I've polled Cisco routers successfully before, haven't confirmed against a switch.
> 
> One thing I'm working on is forks to better suit vendor appliances.
> e.g. Cisco specific - using Cisco-Process-MIB to return additional more meaningful metrics.
> 
> I'll keep you updated

@BraydenNeale 
Thank you very much, I will wait for your notice.

**Comment by fenghaimeng** [comment] 2019-03-19 05:58
> I'll have to validate against a switch when I'm onsite again.
> There could be an issue with trying to pull back metrics from so many interfaces, I've polled Cisco routers successfully before, haven't confirmed against a switch.
> 
> One thing I'm working on is forks to better suit vendor appliances.
> e.g. Cisco specific - using Cisco-Process-MIB to return additional more meaningful metrics.
> 
> I'll keep you updated

@BraydenNeale 
How long will you be able to complete and publish?

**Comment by BraydenNeale** [comment] 2019-03-20 05:31
I can confirm the extension is working against Cisco Nexus 9396 switches for interface metrics.
We have some other models I'll also verify against.

**Comment by fenghaimeng** [comment] 2019-03-26 08:05
> I can confirm the extension is working against Cisco Nexus 9396 switches for interface metrics.
> We have some other models I'll also verify against.

@BraydenNeale 
Have you released a new version?

**Comment by xoraes** [comment] 2019-04-04 19:24
@BraydenNeale I tried your extension and see the same issue when running against a cisco nexus 5000 switch. I also tried increasing the timeout and retry to 60 and 3 respectively but the UI timed out earlier than that.

**Comment by BraydenNeale** [comment] 2019-04-05 02:55
Thanks xoraes,

I haven't had much access to Cisco switches to develop against. Should have some available time next week to test this on site.
Might be some improvements and refinements I can make for interface scalability.
I also plan to test Cisco-Process-MIB

**Comment by BraydenNeale** [comment] 2019-04-09 02:35
Hi All,

Could you try the latest extension release v1.007:
https://github.com/BraydenNeale/Dynatrace-SNMP/releases/tag/1.007

I just added support for polling CPU and Memory utilisation on cisco devices.

No fix on the Interface metrics just yet

**Comment by BraydenNeale** [comment] 2019-05-18 02:37
Interface stats are now fixed for switches and routers (10GB interfaces) in v1.015
https://github.com/BraydenNeale/Dynatrace-SNMP/releases/tag/1.015

**Closed as completed** 2019-05-18 02:38 UTC
